<?php 
require_once("controller.php");
require_once("index.php");
require_once("header.php");
require_once("menu.php");
require_once("event.php");   
require_once("chefs.php");
require_once("gallery.php");
require_once("contact.php");
require_once("contect.php");
require_once("about.php");
require_once("footer.php");                
?>  